# Generated by Django 5.2.18 on 2026-10-08 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.CharField(help_text='Space-separated addresses and ranges', max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ok', 'OK'), ('partial', 'Partial'), ('error', 'Error'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='What went wrong, if anything')),
                ('output', models.JSONField(blank=True, help_text='The validated wall-scan document', null=True)),
                ('stderr', models.TextField(blank=True)),
                ('device_count', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('mac', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('open_ports', models.JSONField(blank=True, help_text='From the last port scan; null if never port-scanned', null=True)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('last_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.scan')),
            ],
        ),
    ]
