# Generated by Django 5.2.18 on 2026-10-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('computer', 'Computer'), ('server', 'Server'), ('printer', 'Printer'), ('network', 'Network equipment'), ('phone', 'Phone or tablet'), ('other', 'Other')], default='unknown', max_length=10, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='A friendly name, e.g. Reception printer', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='warranty_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.location'),
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Microsoft 365 Business Standard', max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('licence_key', models.TextField(blank=True)),
                ('seats', models.PositiveIntegerField(blank=True, help_text='Empty: unlimited', null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, help_text='Empty: does not expire', null=True)),
                ('notes', models.TextField(blank=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='licences', to='inventory.device')),
                ('people', models.ManyToManyField(blank=True, related_name='licences', to='inventory.person')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='inventory.person'),
        ),
    ]
