# Generated by Django 5.2.18 on 2026-10-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='automatic',
            field=models.BooleanField(default=False, help_text='Started by the schedule'),
        ),
        migrations.AddField(
            model_name='scan',
            name='local',
            field=models.BooleanField(default=False, help_text='Also scan the networks the scanner is attached to (--local)'),
        ),
        migrations.AddField(
            model_name='scan',
            name='ports',
            field=models.BooleanField(default=True, help_text='Check open ports; off: discovery only'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('down', 'Down'), ('up', 'Back up'), ('new', 'New device')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scan',
            name='targets',
            field=models.CharField(blank=True, help_text='Space-separated addresses and ranges', max_length=500),
        ),
    ]
