# Generated by Django 5.2.18 on 2026-10-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_scans'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='low_supplies',
            field=models.JSONField(blank=True, default=list, help_text='Indexes of supplies already reported as low'),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_enabled',
            field=models.BooleanField(blank=True, help_text='Empty: automatic, on for printers and network equipment', null=True, verbose_name='read with SNMP'),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_info',
            field=models.JSONField(blank=True, help_text='The result of the last successful read', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_message',
            field=models.TextField(blank=True, help_text='What went wrong in the last read'),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_status',
            field=models.CharField(blank=True, help_text='Empty: never read', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('down', 'Down'), ('up', 'Back up'), ('new', 'New device'), ('supply', 'Supply low')], max_length=10),
        ),
    ]
