# Generated by Django 5.2.18 on 2026-10-10 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_snmp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(help_text='The MAC address the packets were for', max_length=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('waiting', 'Waiting for the device'), ('awake', 'Awake'), ('no_answer', 'No answer'), ('sent', 'Sent'), ('error', 'Error'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('broadcast', models.GenericIPAddressField(blank=True, help_text='Where the packets were sent', null=True, protocol='IPv4')),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text="The hub's address they left from", null=True, protocol='IPv4')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checks', models.PositiveIntegerField(default=0, help_text='Checks made after sending')),
                ('message', models.TextField(blank=True)),
                ('output', models.JSONField(blank=True, help_text='The validated wall-wol document', null=True)),
                ('stderr', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wakes', to='inventory.device')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
